//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign3Part2WebApp.service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.WebserviceSoap")]
    public interface WebserviceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Assign3Part2WebApp.service.HelloWorldResponse HelloWorld(Assign3Part2WebApp.service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.HelloWorldResponse> HelloWorldAsync(Assign3Part2WebApp.service.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name uname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validate_login", ReplyAction="*")]
        Assign3Part2WebApp.service.validate_loginResponse validate_login(Assign3Part2WebApp.service.validate_loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validate_login", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.validate_loginResponse> validate_loginAsync(Assign3Part2WebApp.service.validate_loginRequest request);
        
        // CODEGEN: Generating message contract since element name itemdisplayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemdisplay", ReplyAction="*")]
        Assign3Part2WebApp.service.itemdisplayResponse itemdisplay(Assign3Part2WebApp.service.itemdisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemdisplay", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.itemdisplayResponse> itemdisplayAsync(Assign3Part2WebApp.service.itemdisplayRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encrypt", ReplyAction="*")]
        Assign3Part2WebApp.service.encryptResponse encrypt(Assign3Part2WebApp.service.encryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.encryptResponse> encryptAsync(Assign3Part2WebApp.service.encryptRequest request);
        
        // CODEGEN: Generating message contract since element name decrypt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/decrypt", ReplyAction="*")]
        Assign3Part2WebApp.service.decryptResponse decrypt(Assign3Part2WebApp.service.decryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/decrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.decryptResponse> decryptAsync(Assign3Part2WebApp.service.decryptRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addtoCart", ReplyAction="*")]
        Assign3Part2WebApp.service.addtoCartResponse addtoCart(Assign3Part2WebApp.service.addtoCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addtoCart", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.addtoCartResponse> addtoCartAsync(Assign3Part2WebApp.service.addtoCartRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retrieveCart", ReplyAction="*")]
        Assign3Part2WebApp.service.retrieveCartResponse retrieveCart(Assign3Part2WebApp.service.retrieveCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retrieveCart", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.retrieveCartResponse> retrieveCartAsync(Assign3Part2WebApp.service.retrieveCartRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerUser", ReplyAction="*")]
        Assign3Part2WebApp.service.registerUserResponse registerUser(Assign3Part2WebApp.service.registerUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.registerUserResponse> registerUserAsync(Assign3Part2WebApp.service.registerUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Assign3Part2WebApp.service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Assign3Part2WebApp.service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validate_loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validate_login", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.validate_loginRequestBody Body;
        
        public validate_loginRequest() {
        }
        
        public validate_loginRequest(Assign3Part2WebApp.service.validate_loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validate_loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validate_loginRequestBody() {
        }
        
        public validate_loginRequestBody(string uname, string password) {
            this.uname = uname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validate_loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validate_loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.validate_loginResponseBody Body;
        
        public validate_loginResponse() {
        }
        
        public validate_loginResponse(Assign3Part2WebApp.service.validate_loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validate_loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validate_loginResult;
        
        public validate_loginResponseBody() {
        }
        
        public validate_loginResponseBody(bool validate_loginResult) {
            this.validate_loginResult = validate_loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemdisplayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="itemdisplay", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.itemdisplayRequestBody Body;
        
        public itemdisplayRequest() {
        }
        
        public itemdisplayRequest(Assign3Part2WebApp.service.itemdisplayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class itemdisplayRequestBody {
        
        public itemdisplayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemdisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="itemdisplayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.itemdisplayResponseBody Body;
        
        public itemdisplayResponse() {
        }
        
        public itemdisplayResponse(Assign3Part2WebApp.service.itemdisplayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class itemdisplayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assign3Part2WebApp.service.ArrayOfString itemdisplayResult;
        
        public itemdisplayResponseBody() {
        }
        
        public itemdisplayResponseBody(Assign3Part2WebApp.service.ArrayOfString itemdisplayResult) {
            this.itemdisplayResult = itemdisplayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class encryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="encrypt", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.encryptRequestBody Body;
        
        public encryptRequest() {
        }
        
        public encryptRequest(Assign3Part2WebApp.service.encryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class encryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public encryptRequestBody() {
        }
        
        public encryptRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class encryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="encryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.encryptResponseBody Body;
        
        public encryptResponse() {
        }
        
        public encryptResponse(Assign3Part2WebApp.service.encryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class encryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptResult;
        
        public encryptResponseBody() {
        }
        
        public encryptResponseBody(string encryptResult) {
            this.encryptResult = encryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class decryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="decrypt", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.decryptRequestBody Body;
        
        public decryptRequest() {
        }
        
        public decryptRequest(Assign3Part2WebApp.service.decryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class decryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decrypt;
        
        public decryptRequestBody() {
        }
        
        public decryptRequestBody(string decrypt) {
            this.decrypt = decrypt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class decryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="decryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.decryptResponseBody Body;
        
        public decryptResponse() {
        }
        
        public decryptResponse(Assign3Part2WebApp.service.decryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class decryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decryptResult;
        
        public decryptResponseBody() {
        }
        
        public decryptResponseBody(string decryptResult) {
            this.decryptResult = decryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addtoCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addtoCart", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.addtoCartRequestBody Body;
        
        public addtoCartRequest() {
        }
        
        public addtoCartRequest(Assign3Part2WebApp.service.addtoCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addtoCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string quantity;
        
        public addtoCartRequestBody() {
        }
        
        public addtoCartRequestBody(string userId, string item, string quantity) {
            this.userId = userId;
            this.item = item;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addtoCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addtoCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.addtoCartResponseBody Body;
        
        public addtoCartResponse() {
        }
        
        public addtoCartResponse(Assign3Part2WebApp.service.addtoCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addtoCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addtoCartResult;
        
        public addtoCartResponseBody() {
        }
        
        public addtoCartResponseBody(bool addtoCartResult) {
            this.addtoCartResult = addtoCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieveCart", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.retrieveCartRequestBody Body;
        
        public retrieveCartRequest() {
        }
        
        public retrieveCartRequest(Assign3Part2WebApp.service.retrieveCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retrieveCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public retrieveCartRequestBody() {
        }
        
        public retrieveCartRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieveCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.retrieveCartResponseBody Body;
        
        public retrieveCartResponse() {
        }
        
        public retrieveCartResponse(Assign3Part2WebApp.service.retrieveCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retrieveCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assign3Part2WebApp.service.ArrayOfString retrieveCartResult;
        
        public retrieveCartResponseBody() {
        }
        
        public retrieveCartResponseBody(Assign3Part2WebApp.service.ArrayOfString retrieveCartResult) {
            this.retrieveCartResult = retrieveCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUser", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.registerUserRequestBody Body;
        
        public registerUserRequest() {
        }
        
        public registerUserRequest(Assign3Part2WebApp.service.registerUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public registerUserRequestBody() {
        }
        
        public registerUserRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assign3Part2WebApp.service.registerUserResponseBody Body;
        
        public registerUserResponse() {
        }
        
        public registerUserResponse(Assign3Part2WebApp.service.registerUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registerUserResponseBody {
        
        public registerUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebserviceSoapChannel : Assign3Part2WebApp.service.WebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebserviceSoapClient : System.ServiceModel.ClientBase<Assign3Part2WebApp.service.WebserviceSoap>, Assign3Part2WebApp.service.WebserviceSoap {
        
        public WebserviceSoapClient() {
        }
        
        public WebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.HelloWorldResponse Assign3Part2WebApp.service.WebserviceSoap.HelloWorld(Assign3Part2WebApp.service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Assign3Part2WebApp.service.HelloWorldRequest inValue = new Assign3Part2WebApp.service.HelloWorldRequest();
            inValue.Body = new Assign3Part2WebApp.service.HelloWorldRequestBody();
            Assign3Part2WebApp.service.HelloWorldResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.HelloWorldResponse> Assign3Part2WebApp.service.WebserviceSoap.HelloWorldAsync(Assign3Part2WebApp.service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.HelloWorldResponse> HelloWorldAsync() {
            Assign3Part2WebApp.service.HelloWorldRequest inValue = new Assign3Part2WebApp.service.HelloWorldRequest();
            inValue.Body = new Assign3Part2WebApp.service.HelloWorldRequestBody();
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.validate_loginResponse Assign3Part2WebApp.service.WebserviceSoap.validate_login(Assign3Part2WebApp.service.validate_loginRequest request) {
            return base.Channel.validate_login(request);
        }
        
        public bool validate_login(string uname, string password) {
            Assign3Part2WebApp.service.validate_loginRequest inValue = new Assign3Part2WebApp.service.validate_loginRequest();
            inValue.Body = new Assign3Part2WebApp.service.validate_loginRequestBody();
            inValue.Body.uname = uname;
            inValue.Body.password = password;
            Assign3Part2WebApp.service.validate_loginResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).validate_login(inValue);
            return retVal.Body.validate_loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.validate_loginResponse> Assign3Part2WebApp.service.WebserviceSoap.validate_loginAsync(Assign3Part2WebApp.service.validate_loginRequest request) {
            return base.Channel.validate_loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.validate_loginResponse> validate_loginAsync(string uname, string password) {
            Assign3Part2WebApp.service.validate_loginRequest inValue = new Assign3Part2WebApp.service.validate_loginRequest();
            inValue.Body = new Assign3Part2WebApp.service.validate_loginRequestBody();
            inValue.Body.uname = uname;
            inValue.Body.password = password;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).validate_loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.itemdisplayResponse Assign3Part2WebApp.service.WebserviceSoap.itemdisplay(Assign3Part2WebApp.service.itemdisplayRequest request) {
            return base.Channel.itemdisplay(request);
        }
        
        public Assign3Part2WebApp.service.ArrayOfString itemdisplay() {
            Assign3Part2WebApp.service.itemdisplayRequest inValue = new Assign3Part2WebApp.service.itemdisplayRequest();
            inValue.Body = new Assign3Part2WebApp.service.itemdisplayRequestBody();
            Assign3Part2WebApp.service.itemdisplayResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).itemdisplay(inValue);
            return retVal.Body.itemdisplayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.itemdisplayResponse> Assign3Part2WebApp.service.WebserviceSoap.itemdisplayAsync(Assign3Part2WebApp.service.itemdisplayRequest request) {
            return base.Channel.itemdisplayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.itemdisplayResponse> itemdisplayAsync() {
            Assign3Part2WebApp.service.itemdisplayRequest inValue = new Assign3Part2WebApp.service.itemdisplayRequest();
            inValue.Body = new Assign3Part2WebApp.service.itemdisplayRequestBody();
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).itemdisplayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.encryptResponse Assign3Part2WebApp.service.WebserviceSoap.encrypt(Assign3Part2WebApp.service.encryptRequest request) {
            return base.Channel.encrypt(request);
        }
        
        public string encrypt(string str) {
            Assign3Part2WebApp.service.encryptRequest inValue = new Assign3Part2WebApp.service.encryptRequest();
            inValue.Body = new Assign3Part2WebApp.service.encryptRequestBody();
            inValue.Body.str = str;
            Assign3Part2WebApp.service.encryptResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).encrypt(inValue);
            return retVal.Body.encryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.encryptResponse> Assign3Part2WebApp.service.WebserviceSoap.encryptAsync(Assign3Part2WebApp.service.encryptRequest request) {
            return base.Channel.encryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.encryptResponse> encryptAsync(string str) {
            Assign3Part2WebApp.service.encryptRequest inValue = new Assign3Part2WebApp.service.encryptRequest();
            inValue.Body = new Assign3Part2WebApp.service.encryptRequestBody();
            inValue.Body.str = str;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).encryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.decryptResponse Assign3Part2WebApp.service.WebserviceSoap.decrypt(Assign3Part2WebApp.service.decryptRequest request) {
            return base.Channel.decrypt(request);
        }
        
        public string decrypt(string decrypt1) {
            Assign3Part2WebApp.service.decryptRequest inValue = new Assign3Part2WebApp.service.decryptRequest();
            inValue.Body = new Assign3Part2WebApp.service.decryptRequestBody();
            inValue.Body.decrypt = decrypt1;
            Assign3Part2WebApp.service.decryptResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).decrypt(inValue);
            return retVal.Body.decryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.decryptResponse> Assign3Part2WebApp.service.WebserviceSoap.decryptAsync(Assign3Part2WebApp.service.decryptRequest request) {
            return base.Channel.decryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.decryptResponse> decryptAsync(string decrypt) {
            Assign3Part2WebApp.service.decryptRequest inValue = new Assign3Part2WebApp.service.decryptRequest();
            inValue.Body = new Assign3Part2WebApp.service.decryptRequestBody();
            inValue.Body.decrypt = decrypt;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).decryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.addtoCartResponse Assign3Part2WebApp.service.WebserviceSoap.addtoCart(Assign3Part2WebApp.service.addtoCartRequest request) {
            return base.Channel.addtoCart(request);
        }
        
        public bool addtoCart(string userId, string item, string quantity) {
            Assign3Part2WebApp.service.addtoCartRequest inValue = new Assign3Part2WebApp.service.addtoCartRequest();
            inValue.Body = new Assign3Part2WebApp.service.addtoCartRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.item = item;
            inValue.Body.quantity = quantity;
            Assign3Part2WebApp.service.addtoCartResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).addtoCart(inValue);
            return retVal.Body.addtoCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.addtoCartResponse> Assign3Part2WebApp.service.WebserviceSoap.addtoCartAsync(Assign3Part2WebApp.service.addtoCartRequest request) {
            return base.Channel.addtoCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.addtoCartResponse> addtoCartAsync(string userId, string item, string quantity) {
            Assign3Part2WebApp.service.addtoCartRequest inValue = new Assign3Part2WebApp.service.addtoCartRequest();
            inValue.Body = new Assign3Part2WebApp.service.addtoCartRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.item = item;
            inValue.Body.quantity = quantity;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).addtoCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.retrieveCartResponse Assign3Part2WebApp.service.WebserviceSoap.retrieveCart(Assign3Part2WebApp.service.retrieveCartRequest request) {
            return base.Channel.retrieveCart(request);
        }
        
        public Assign3Part2WebApp.service.ArrayOfString retrieveCart(string userId) {
            Assign3Part2WebApp.service.retrieveCartRequest inValue = new Assign3Part2WebApp.service.retrieveCartRequest();
            inValue.Body = new Assign3Part2WebApp.service.retrieveCartRequestBody();
            inValue.Body.userId = userId;
            Assign3Part2WebApp.service.retrieveCartResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).retrieveCart(inValue);
            return retVal.Body.retrieveCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.retrieveCartResponse> Assign3Part2WebApp.service.WebserviceSoap.retrieveCartAsync(Assign3Part2WebApp.service.retrieveCartRequest request) {
            return base.Channel.retrieveCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.retrieveCartResponse> retrieveCartAsync(string userId) {
            Assign3Part2WebApp.service.retrieveCartRequest inValue = new Assign3Part2WebApp.service.retrieveCartRequest();
            inValue.Body = new Assign3Part2WebApp.service.retrieveCartRequestBody();
            inValue.Body.userId = userId;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).retrieveCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assign3Part2WebApp.service.registerUserResponse Assign3Part2WebApp.service.WebserviceSoap.registerUser(Assign3Part2WebApp.service.registerUserRequest request) {
            return base.Channel.registerUser(request);
        }
        
        public void registerUser(string str) {
            Assign3Part2WebApp.service.registerUserRequest inValue = new Assign3Part2WebApp.service.registerUserRequest();
            inValue.Body = new Assign3Part2WebApp.service.registerUserRequestBody();
            inValue.Body.str = str;
            Assign3Part2WebApp.service.registerUserResponse retVal = ((Assign3Part2WebApp.service.WebserviceSoap)(this)).registerUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assign3Part2WebApp.service.registerUserResponse> Assign3Part2WebApp.service.WebserviceSoap.registerUserAsync(Assign3Part2WebApp.service.registerUserRequest request) {
            return base.Channel.registerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assign3Part2WebApp.service.registerUserResponse> registerUserAsync(string str) {
            Assign3Part2WebApp.service.registerUserRequest inValue = new Assign3Part2WebApp.service.registerUserRequest();
            inValue.Body = new Assign3Part2WebApp.service.registerUserRequestBody();
            inValue.Body.str = str;
            return ((Assign3Part2WebApp.service.WebserviceSoap)(this)).registerUserAsync(inValue);
        }
    }
}
